---
- name: First playbook - Set and print fact
  hosts: all
  gather_facts: false

  tasks:
    - name: Set example fact
      ansible.builtin.set_fact:
        example_variable: "FIRST PLAYBOOK VARIABLE"

    - name: Print the fact from first playbook
      ansible.builtin.debug:
        msg: "First playbook - example_variable: {{ example_variable }}"
