---
- name: Set example fact
  ansible.builtin.set_fact:
    example_variable: "FIRST TASKS LIST VARIABLE"

- name: Print the fact from first playbook
  ansible.builtin.debug:
    msg: "First playbook - example_variable: {{ example_variable }}"
